# permissions for end users to view oracleclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oraclecluster-viewer-role
rules:
- apiGroups:
  - oracle.iwhalecloud.com
  resources:
  - oracleclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.iwhalecloud.com
  resources:
  - oracleclusters/status
  verbs:
  - get
