# permissions for end users to edit oraclebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oraclebackup-editor-role
rules:
- apiGroups:
  - oracle.iwhalecloud.com
  resources:
  - oraclebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.iwhalecloud.com
  resources:
  - oraclebackups/status
  verbs:
  - get
