# permissions for end users to edit oraclerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oraclerestore-editor-role
rules:
- apiGroups:
  - oracle.iwhalecloud.com
  resources:
  - oraclerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.iwhalecloud.com
  resources:
  - oraclerestores/status
  verbs:
  - get
