apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oracle-operator
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oraclebackups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oraclebackups/finalizers
    verbs:
      - update
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oraclebackups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oracleclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oracleclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oracleclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oraclerestores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oraclerestores/finalizers
    verbs:
      - update
  - apiGroups:
      - oracle.iwhalecloud.com
    resources:
      - oraclerestores/status
    verbs:
      - get
      - patch
      - update