apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oracle-operator-leader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oracle-operator-leader
subjects:
- kind: ServiceAccount
  name: oracle-operator
  namespace: default
