apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-operator
  labels:
    app: oracle-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oracle-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oracle-operator
    spec:
      serviceAccountName: oracle-operator
      containers:
        - name: operator
          image: 10.10.236.107:8099/k8s/oracle/oracle-operator:0.1
          args:
            - -cli-image=10.10.236.107:8099/oracle/instantclient:19-gotty-3
            - -namespace=default
            - -leader-elect=true
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
          ports:
            - containerPort: 8081
              name: health
              protocol: TCP